# Generated by Django 5.1 on 2024-08-22 04:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinoBioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bioma',
                'verbose_name_plural': 'Biomas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DinoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DinoEpoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Epoca',
                'verbose_name_plural': 'Epocas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DinoTipoDeDino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinoNome', models.CharField(max_length=100)),
                ('dinoDescricao', models.TextField()),
                ('dinoTamanhoMin', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dinoTamanhoMax', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dinoPesoMin', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dinoPesoMax', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dinoImage', models.ImageField(upload_to='images/')),
                ('dinoCreateDate', models.DateTimeField(auto_now_add=True)),
                ('biomas', models.ManyToManyField(to='post_app.dinobioma')),
                ('dinoDieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinodieta')),
                ('dinoEpoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinoepoca')),
                ('dinoTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.dinotipodedino')),
            ],
            options={
                'verbose_name': 'Criatura',
                'verbose_name_plural': 'Criaturas',
                'ordering': ['id'],
            },
        ),
    ]
